// Code generated by protoc-gen-go. DO NOT EDIT.
// source: my_service.proto

package myservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EServer struct {
	Server               string   `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EServer) Reset()         { *m = EServer{} }
func (m *EServer) String() string { return proto.CompactTextString(m) }
func (*EServer) ProtoMessage()    {}
func (*EServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_a845ab241122eea0, []int{0}
}

func (m *EServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EServer.Unmarshal(m, b)
}
func (m *EServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EServer.Marshal(b, m, deterministic)
}
func (m *EServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EServer.Merge(m, src)
}
func (m *EServer) XXX_Size() int {
	return xxx_messageInfo_EServer.Size(m)
}
func (m *EServer) XXX_DiscardUnknown() {
	xxx_messageInfo_EServer.DiscardUnknown(m)
}

var xxx_messageInfo_EServer proto.InternalMessageInfo

func (m *EServer) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

type Result struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_a845ab241122eea0, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Result) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Query struct {
	Server               string   `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Query                string   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Index                string   `protobuf:"bytes,3,opt,name=index,proto3" json:"index,omitempty"`
	Term                 string   `protobuf:"bytes,4,opt,name=term,proto3" json:"term,omitempty"`
	Start                int32    `protobuf:"varint,5,opt,name=start,proto3" json:"start,omitempty"`
	Size                 int32    `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_a845ab241122eea0, []int{2}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *Query) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *Query) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Query) GetTerm() string {
	if m != nil {
		return m.Term
	}
	return ""
}

func (m *Query) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Query) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type QueryResult struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Results              string   `protobuf:"bytes,3,opt,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResult) Reset()         { *m = QueryResult{} }
func (m *QueryResult) String() string { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()    {}
func (*QueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a845ab241122eea0, []int{3}
}

func (m *QueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResult.Unmarshal(m, b)
}
func (m *QueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResult.Marshal(b, m, deterministic)
}
func (m *QueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResult.Merge(m, src)
}
func (m *QueryResult) XXX_Size() int {
	return xxx_messageInfo_QueryResult.Size(m)
}
func (m *QueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResult proto.InternalMessageInfo

func (m *QueryResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryResult) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *QueryResult) GetResults() string {
	if m != nil {
		return m.Results
	}
	return ""
}

func init() {
	proto.RegisterType((*EServer)(nil), "myservice.EServer")
	proto.RegisterType((*Result)(nil), "myservice.Result")
	proto.RegisterType((*Query)(nil), "myservice.Query")
	proto.RegisterType((*QueryResult)(nil), "myservice.QueryResult")
}

func init() { proto.RegisterFile("my_service.proto", fileDescriptor_a845ab241122eea0) }

var fileDescriptor_a845ab241122eea0 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0xb5, 0x49, 0xc9, 0x08, 0x52, 0x97, 0x52, 0x96, 0x9e, 0x34, 0xa7, 0x9e, 0x82, 0xf8,
	0x01, 0x9e, 0x0b, 0x52, 0x7a, 0x10, 0x6b, 0xf2, 0x03, 0x24, 0xdd, 0xcc, 0x21, 0x90, 0x34, 0xba,
	0x3b, 0x29, 0xc6, 0x7f, 0xe0, 0xdf, 0xf1, 0x17, 0xca, 0xce, 0xa6, 0x1f, 0x08, 0x0a, 0xbd, 0xbd,
	0xf7, 0xf2, 0x5e, 0xf6, 0xcd, 0x30, 0x30, 0xac, 0xda, 0x57, 0x83, 0x7a, 0x53, 0x28, 0x8c, 0xdf,
	0x74, 0x4d, 0xb5, 0x08, 0xab, 0xb6, 0x13, 0xa2, 0x2b, 0x18, 0x3c, 0xa6, 0xa8, 0x37, 0xa8, 0xc5,
	0x18, 0x02, 0xc3, 0x48, 0x7a, 0x97, 0xde, 0x34, 0x4c, 0x3a, 0x16, 0x5d, 0x43, 0x90, 0xa0, 0x69,
	0x4a, 0x12, 0x02, 0xfa, 0xaa, 0xce, 0x91, 0xbf, 0xfb, 0x09, 0x63, 0xab, 0xe5, 0x19, 0x65, 0xb2,
	0xc7, 0x19, 0xc6, 0xd1, 0x97, 0x07, 0xfe, 0x4b, 0x83, 0xba, 0xfd, 0xeb, 0x9f, 0x62, 0x04, 0xfe,
	0xbb, 0x35, 0x74, 0x31, 0x47, 0xac, 0x5a, 0xac, 0x73, 0xfc, 0x90, 0xa7, 0x4e, 0x65, 0x62, 0x5f,
	0x20, 0xd4, 0x95, 0xec, 0xbb, 0x17, 0x2c, 0xb6, 0x4e, 0x43, 0x99, 0x26, 0xe9, 0x73, 0x15, 0x47,
	0xac, 0xd3, 0x14, 0x9f, 0x28, 0x03, 0xd7, 0xcf, 0xe2, 0xe8, 0x19, 0xce, 0xb8, 0xca, 0xff, 0x23,
	0x70, 0xac, 0xb7, 0x8f, 0x09, 0x09, 0x03, 0xcd, 0x09, 0xd3, 0x95, 0xd9, 0xd2, 0x9b, 0x6f, 0x0f,
	0xc2, 0xa7, 0x36, 0x75, 0xfb, 0x13, 0xf7, 0x00, 0x73, 0xa4, 0xc5, 0x3a, 0x2f, 0x14, 0x1a, 0x21,
	0xe2, 0xdd, 0x66, 0xe3, 0x6e, 0xad, 0x93, 0x8b, 0x03, 0xcd, 0x95, 0x88, 0x4e, 0xc4, 0x1d, 0x84,
	0x73, 0xa4, 0x94, 0x32, 0x6a, 0x8e, 0x48, 0x3d, 0x00, 0xf0, 0x2c, 0x0b, 0xde, 0xcb, 0xf0, 0xc0,
	0xc2, 0xf2, 0x64, 0xfc, 0x5b, 0xd9, 0x26, 0x67, 0x53, 0x18, 0xa9, 0xba, 0x8a, 0x57, 0x46, 0x95,
	0xa5, 0xda, 0xbb, 0x66, 0xe7, 0xbb, 0x49, 0x96, 0xf6, 0x32, 0x96, 0xde, 0x2a, 0xe0, 0x13, 0xb9,
	0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x95, 0x5c, 0x4b, 0x13, 0x36, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MyServiceClient is the client API for MyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MyServiceClient interface {
	GetIndices(ctx context.Context, in *EServer, opts ...grpc.CallOption) (*Result, error)
	GetStatus(ctx context.Context, in *EServer, opts ...grpc.CallOption) (*Result, error)
	QueryIndex(ctx context.Context, in *Query, opts ...grpc.CallOption) (*QueryResult, error)
}

type myServiceClient struct {
	cc *grpc.ClientConn
}

func NewMyServiceClient(cc *grpc.ClientConn) MyServiceClient {
	return &myServiceClient{cc}
}

func (c *myServiceClient) GetIndices(ctx context.Context, in *EServer, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/myservice.MyService/GetIndices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServiceClient) GetStatus(ctx context.Context, in *EServer, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/myservice.MyService/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServiceClient) QueryIndex(ctx context.Context, in *Query, opts ...grpc.CallOption) (*QueryResult, error) {
	out := new(QueryResult)
	err := c.cc.Invoke(ctx, "/myservice.MyService/QueryIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyServiceServer is the server API for MyService service.
type MyServiceServer interface {
	GetIndices(context.Context, *EServer) (*Result, error)
	GetStatus(context.Context, *EServer) (*Result, error)
	QueryIndex(context.Context, *Query) (*QueryResult, error)
}

// UnimplementedMyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMyServiceServer struct {
}

func (*UnimplementedMyServiceServer) GetIndices(ctx context.Context, req *EServer) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIndices not implemented")
}
func (*UnimplementedMyServiceServer) GetStatus(ctx context.Context, req *EServer) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (*UnimplementedMyServiceServer) QueryIndex(ctx context.Context, req *Query) (*QueryResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryIndex not implemented")
}

func RegisterMyServiceServer(s *grpc.Server, srv MyServiceServer) {
	s.RegisterService(&_MyService_serviceDesc, srv)
}

func _MyService_GetIndices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EServer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).GetIndices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myservice.MyService/GetIndices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).GetIndices(ctx, req.(*EServer))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EServer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myservice.MyService/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).GetStatus(ctx, req.(*EServer))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyService_QueryIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServiceServer).QueryIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myservice.MyService/QueryIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServiceServer).QueryIndex(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "myservice.MyService",
	HandlerType: (*MyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIndices",
			Handler:    _MyService_GetIndices_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _MyService_GetStatus_Handler,
		},
		{
			MethodName: "QueryIndex",
			Handler:    _MyService_QueryIndex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "my_service.proto",
}
